theme: coder
baseURL: https://hackerdrinks.sg
languageCode: en-us
title: hackerdrinks
metaDataFormat: yaml
publishDir: ../public
googleAnalytics: UA-117111154-1
menu:
  main:
  - name: "past events"
    url: "/events"
params:
  author: hackerdrinks
  info: a gossip-consensus, social networking protocol, facilitated by alcohol
  next:
    date1: "07 Apr 2022"
    date2: Thursday
    date3: 7.00pm
    venue1: "Bluemist Cafe and Bistro"
    venue1Link: https://shield.com
    venue2: "Blk 7 Tanjong Pagar Plaza"
    venue3: "#01-103"
    venue4: "Singapore 081007"
  instances: 2
  social:
   github:
     name: Github
     url: https://github.com/hackerdrinks-sg
   instagram:
     name: Instagram
     url: https://www.instagram.com/hackerdrinks
