theme: coder
baseURL: https://hackerdrinks.sg
languageCode: en-us
title: hackerdrinks
metaDataFormat: yaml
publishDir: ../public
googleAnalytics: UA-117111154-1
params:
  author: hackerdrinks
  info: a gossip-consensus, social networking protocol, facilitated by alcohol
  next:
    date: 20 June 2019, Thu, 7pm
    venue: "Referral Candy, Blk 71 Ayer Rajah Crescent, #06-26, Singapore 139951"
  instances: 2
  social:
   github:
     name: Github
     url: https://github.com/hackerdrinks-sg