theme: coder
baseURL: https://hackerdrinks.sg
languageCode: en-us
title: hackerdrinks
metaDataFormat: yaml
publishDir: ../public
googleAnalytics: UA-117111154-1
menu:
  main:
  - name: "past events"
    url: "/events"
params:
  author: hackerdrinks
  info: a non-fungible, gossip-consensus, social networking protocol, facilitated by alcohol
  social:
   github:
     name: Github
     url: https://github.com/hackerdrinks-sg
   instagram:
     name: Instagram
     url: https://www.instagram.com/hackerdrinks
