theme: coder
baseURL: https://hackerdrinks.sg
languageCode: en-us
title: hackerdrinks
metaDataFormat: yaml
publishDir: ../public
googleAnalytics: UA-117111154-1
params:
  author: hackerdrinks
  info: a gossip-consensus, social networking protocol, facilitated by alcohol
  next:
    date1: 20 June 2019
    date2: Thursday
    date3: 7pm
    venue1: "Referral Candy"
    venue2: "Blk 71 Ayer Rajah Crescent"
    venue3: "#06-26"
    venue4: "Singapore 139951"
  instances: 2
  social:
   github:
     name: Github
     url: https://github.com/hackerdrinks-sg