theme: coder
baseURL: https://hackerdrinks.sg
languageCode: en-us
title: hackerdrinks
metaDataFormat: yaml
publishDir: ../public
googleAnalytics: UA-117111154-1
params:
  author: hackerdrinks
  info: a gossip-consensus, social networking protocol, facilitated by alcohol
  next:
    date: 2 Aug 2018, Thursday, 7pm
    venue: "Bluemist Cafe, 7 Tanjong Pagar Plaza #01-03, Singapore 081007"
  social:
   github:
     name: Github
     url: https://github.com/hackerdrinks-sg

